image: moodlehq/moodle-php-apache:7.4

services:
  - postgres:10
  #- mysql:5.7.26
  - name: selenium/standalone-chrome:3
    alias: selenium-standalone-chrome

variables:
  MOODLE_REPO: https://github.com/moodle/moodle.git
  MOODLE_BRANCH: MOODLE_400_STABLE
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  NVM_DIR: /usr/local/nvm
  DB: "pgsql"
#  DB: "mysqli"

lms:
  script:
    # Dockerfile
    - |
      cd ~
      apt update && apt install -y -q --no-install-recommends \
        openjdk-11-jre-headless \
        git-core \
        ssh-client \
        default-mysql-client \
        postgresql-client \
        rsync \
        && apt clean
      export NODE_VERSION_INSTALL=16.15.1
      mkdir $NVM_DIR || true
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash \
         && . $NVM_DIR/nvm.sh \
         && nvm install $NODE_VERSION_INSTALL
      export NODE_PATH=$NVM_DIR/versions/node/v$NODE_VERSION_INSTALL/lib/node_modules
      export PATH=$NVM_DIR/versions/node/v$NODE_VERSION_INSTALL/bin:$PATH
      curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
      composer create-project -v -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci 3.2.1
      chmod u+x ci/bin/*
      umask u+x
      ln -s `pwd`/ci/bin/moodle-plugin-ci /usr/local/bin
    # Prepare
    - export TRAVIS_BUILD_DIR="$CI_PROJECT_DIR"
    - |
      if [[ "$DB" == "mysqli" ]]; then
          export DB_HOST="mysql"
      elif [[ "$DB" == "pgsql" ]]; then
          export DB_HOST="postgres"
      else
          export DB_HOST="$DB"
      fi
    - export IPADDRESS=`grep "${HOSTNAME}$" /etc/hosts |awk '{print $1}'`
    - export MOODLE_BEHAT_WWWROOT="http://${IPADDRESS}:8000"
    - export MOODLE_START_BEHAT_SERVERS="NO"
    - . $NVM_DIR/nvm.sh
    # Script
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    - php admin/tool/behat/cli/init.php
    - moodle-plugin-ci phplint
    #- moodle-plugin-ci phpcpd
    #- moodle-plugin-ci phpmd
    - moodle-plugin-ci codechecker --max-warnings 0
    - moodle-plugin-ci phpdoc
    - moodle-plugin-ci validate
    - moodle-plugin-ci savepoints
    - moodle-plugin-ci mustache
    - moodle-plugin-ci grunt --max-lint-warnings 0
    - vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_dataprivacy_testsuite --filter metadata_registry_test
    - vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_testsuite --filter test_all_external_info
    #- vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_test
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci behat --suite default --profile chrome
